
package hotelreserve;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Point;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionAdapter;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.GroupLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.LayoutStyle;
import javax.swing.SwingConstants;
import javax.swing.WindowConstants;

/**
 *
 * @author Villosa
 */
public class GuestOptionFrame extends javax.swing.JFrame {
    
    private int xMouse, yMouse;
    private Hotel database = new Hotel();
    /**
     * Creates new form OptionFrame
     */
    public GuestOptionFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new JPanel();
        jPanel2 = new JPanel();
        manageAccountButton = new JButton();
        reserveRoomsButton = new JButton();
        WelcomGuestLabel = new JLabel();
        jPanel3 = new JPanel();
        jLabel2 = new JLabel();
        TopPanel = new JPanel();
        jLabel3 = new JLabel();
        jLabel4 = new JLabel();
        jLabel5 = new JLabel();
        logoutLabel = new JLabel();
        exitButton = new JLabel();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        setLocation(new Point(300, 100));
        setMinimumSize(new Dimension(200, 200));
        setUndecorated(true);
        setOpacity(0.0F);
        addWindowListener(new WindowAdapter() {
            public void windowOpened(WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new Color(65, 64, 75));

        jPanel2.setBackground(new Color(255, 255, 255));

        manageAccountButton.setBackground(new Color(0, 51, 51));
        manageAccountButton.setFont(new Font("Swis721 LtEx BT", 0, 18)); // NOI18N
        manageAccountButton.setIcon(new ImageIcon(getClass().getResource("/img/ManageBotton_default.PNG"))); // NOI18N
        manageAccountButton.setContentAreaFilled(false);
        manageAccountButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        manageAccountButton.addMouseListener(new MouseAdapter() {
            public void mouseEntered(MouseEvent evt) {
                manageAccountButtonMouseEntered(evt);
            }
            public void mouseExited(MouseEvent evt) {
                manageAccountButtonMouseExited(evt);
            }
            public void mousePressed(MouseEvent evt) {
                manageAccountButtonMousePressed(evt);
            }
            public void mouseReleased(MouseEvent evt) {
                manageAccountButtonMouseReleased(evt);
            }
        });
        manageAccountButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                manageAccountButtonActionPerformed(evt);
            }
        });

        reserveRoomsButton.setBackground(new Color(0, 51, 153));
        reserveRoomsButton.setFont(new Font("Swis721 LtEx BT", 0, 18)); // NOI18N
        reserveRoomsButton.setIcon(new ImageIcon(getClass().getResource("/img/PreferenceBotton_default.png"))); // NOI18N
        reserveRoomsButton.setContentAreaFilled(false);
        reserveRoomsButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        reserveRoomsButton.addMouseListener(new MouseAdapter() {
            public void mouseEntered(MouseEvent evt) {
                reserveRoomsButtonMouseEntered(evt);
            }
            public void mouseExited(MouseEvent evt) {
                reserveRoomsButtonMouseExited(evt);
            }
            public void mousePressed(MouseEvent evt) {
                reserveRoomsButtonMousePressed(evt);
            }
        });
        reserveRoomsButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                reserveRoomsButtonActionPerformed(evt);
            }
        });

        WelcomGuestLabel.setFont(new Font("Swis721 LtEx BT", 0, 18)); // NOI18N
        WelcomGuestLabel.setHorizontalAlignment(SwingConstants.CENTER);
        WelcomGuestLabel.setText("Hello Guest");

        GroupLayout jPanel2Layout = new GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(214, 214, 214)
                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(manageAccountButton, GroupLayout.PREFERRED_SIZE, 193, GroupLayout.PREFERRED_SIZE)
                    .addComponent(reserveRoomsButton, GroupLayout.PREFERRED_SIZE, 191, GroupLayout.PREFERRED_SIZE))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(WelcomGuestLabel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(WelcomGuestLabel)
                .addGap(18, 18, 18)
                .addComponent(manageAccountButton)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(reserveRoomsButton, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(32, 32, 32))
        );

        jLabel2.setIcon(new ImageIcon(getClass().getResource("/img/Reception123.PNG"))); // NOI18N

        GroupLayout jPanel3Layout = new GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        TopPanel.setBackground(new Color(65, 64, 75));
        TopPanel.addMouseMotionListener(new MouseMotionAdapter() {
            public void mouseDragged(MouseEvent evt) {
                TopPanelMouseDragged(evt);
            }
        });
        TopPanel.addMouseListener(new MouseAdapter() {
            public void mousePressed(MouseEvent evt) {
                TopPanelMousePressed(evt);
            }
        });

        jLabel3.setIcon(new ImageIcon(getClass().getResource("/img/midtown2mini.png"))); // NOI18N

        jLabel4.setFont(new Font("Trajan Pro", 0, 16)); // NOI18N
        jLabel4.setForeground(new Color(255, 255, 255));
        jLabel4.setText("Welcome to MidTown Hotel");

        GroupLayout TopPanelLayout = new GroupLayout(TopPanel);
        TopPanel.setLayout(TopPanelLayout);
        TopPanelLayout.setHorizontalGroup(TopPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(TopPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel3)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TopPanelLayout.setVerticalGroup(TopPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, TopPanelLayout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(29, 29, 29))
            .addGroup(TopPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel5.setFont(new Font("Tahoma", 0, 8)); // NOI18N
        jLabel5.setForeground(new Color(153, 153, 153));
        jLabel5.setText("MIDTOWN HOTEL ONLINE RESERVATION SYSTEM © 2015 ");

        logoutLabel.setForeground(new Color(204, 204, 204));
        logoutLabel.setText("LOGOUT");
        logoutLabel.setCursor(new Cursor(Cursor.HAND_CURSOR));
        logoutLabel.addMouseListener(new MouseAdapter() {
            public void mouseEntered(MouseEvent evt) {
                logoutLabelMouseEntered(evt);
            }
            public void mouseExited(MouseEvent evt) {
                logoutLabelMouseExited(evt);
            }
            public void mousePressed(MouseEvent evt) {
                logoutLabelMousePressed(evt);
            }
            public void mouseReleased(MouseEvent evt) {
                logoutLabelMouseReleased(evt);
            }
        });

        exitButton.setIcon(new ImageIcon(getClass().getResource("/img/x_default.png"))); // NOI18N
        exitButton.addMouseListener(new MouseAdapter() {
            public void mouseEntered(MouseEvent evt) {
                exitButtonMouseEntered(evt);
            }
            public void mouseExited(MouseEvent evt) {
                exitButtonMouseExited(evt);
            }
            public void mousePressed(MouseEvent evt) {
                exitButtonMousePressed(evt);
            }
            public void mouseReleased(MouseEvent evt) {
                exitButtonMouseReleased(evt);
            }
        });

        GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(TopPanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(exitButton))
                    .addGroup(GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(logoutLabel)
                        .addContainerGap())))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(201, 201, 201)
                .addComponent(jLabel5)
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(TopPanel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(exitButton)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(logoutLabel)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jPanel3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jLabel5)
                .addGap(14, 14, 14))
        );

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void manageAccountButtonMouseEntered(MouseEvent evt) {//GEN-FIRST:event_manageAccountButtonMouseEntered

        ImageIcon extbot = new ImageIcon(getClass().getResource("/img/ManageBotton_hover.png"));
        manageAccountButton.setIcon(extbot);
        
    }//GEN-LAST:event_manageAccountButtonMouseEntered

    private void manageAccountButtonMouseExited(MouseEvent evt) {//GEN-FIRST:event_manageAccountButtonMouseExited

        ImageIcon extbot = new ImageIcon(getClass().getResource("/img/ManageBotton_default.png"));
        manageAccountButton.setIcon(extbot);
        
    }//GEN-LAST:event_manageAccountButtonMouseExited

    private void reserveRoomsButtonMouseEntered(MouseEvent evt) {//GEN-FIRST:event_reserveRoomsButtonMouseEntered

        ImageIcon extbot = new ImageIcon(getClass().getResource("/img/PreferenceBotton_hover.png"));
        reserveRoomsButton.setIcon(extbot);
    }//GEN-LAST:event_reserveRoomsButtonMouseEntered
    
    /**
     * When reserveRooms button is clicked, check if the guest have previous room 
     **/
    private void reserveRoomsButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_reserveRoomsButtonActionPerformed

        if(database.getGuestPrevRoomType().equals("none")){
             
           preferenceFrame myPref = new preferenceFrame();
           myPref.displayFrame();
            
           this.setVisible(false);
           this.dispose();
        
        }else{
            
            loadprevFrame reloadRoom = new loadprevFrame();
            reloadRoom.displayFrame();
            
            this.setVisible(false);
            this.dispose();
        }
         
    }//GEN-LAST:event_reserveRoomsButtonActionPerformed

    private void reserveRoomsButtonMouseExited(MouseEvent evt) {//GEN-FIRST:event_reserveRoomsButtonMouseExited

        ImageIcon extbot = new ImageIcon(getClass().getResource("/img/PreferenceBotton_default.png"));
        reserveRoomsButton.setIcon(extbot);
    }//GEN-LAST:event_reserveRoomsButtonMouseExited

    private void manageAccountButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_manageAccountButtonActionPerformed
       ManageAccountsFrame myAccount = new ManageAccountsFrame();
       myAccount.displayFrame();
       this.setVisible(false);
       this.dispose();
    }//GEN-LAST:event_manageAccountButtonActionPerformed
    
    /**
     * When this window is opened, reload the data saved from the file and update
     * the data to this program.
     */
    private void formWindowOpened(WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        WelcomGuestLabel.setText("Welcome " +database.getGuestName());
        
         //fading in
         for(double i=0.0;i<1.0;i=i+0.1){
            String val = i+"F";
            float f = Float.valueOf(val);
            this.setOpacity(f);
            try{
                Thread.sleep(20);
            }catch(Exception e){
            
            }
        }
    }//GEN-LAST:event_formWindowOpened

    private void manageAccountButtonMousePressed(MouseEvent evt) {//GEN-FIRST:event_manageAccountButtonMousePressed
        
        ImageIcon extbot = new ImageIcon(getClass().getResource("/img/ManageBotton_pressed.png"));
        manageAccountButton.setIcon(extbot);
    }//GEN-LAST:event_manageAccountButtonMousePressed

    private void manageAccountButtonMouseReleased(MouseEvent evt) {//GEN-FIRST:event_manageAccountButtonMouseReleased
        
        ImageIcon extbot = new ImageIcon(getClass().getResource("/img/ManageBotton_hover.png"));
       manageAccountButton.setIcon(extbot);
    }//GEN-LAST:event_manageAccountButtonMouseReleased

    private void TopPanelMouseDragged(MouseEvent evt) {//GEN-FIRST:event_TopPanelMouseDragged
        
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        this.setLocation(x-xMouse,y-yMouse);
    }//GEN-LAST:event_TopPanelMouseDragged

    private void TopPanelMousePressed(MouseEvent evt) {//GEN-FIRST:event_TopPanelMousePressed
        
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_TopPanelMousePressed

    private void reserveRoomsButtonMousePressed(MouseEvent evt) {//GEN-FIRST:event_reserveRoomsButtonMousePressed
        
        ImageIcon extbot = new ImageIcon(getClass().getResource("/img/PreferenceBotton_pressed.png"));
        reserveRoomsButton.setIcon(extbot);
    }//GEN-LAST:event_reserveRoomsButtonMousePressed

    private void logoutLabelMouseEntered(MouseEvent evt) {//GEN-FIRST:event_logoutLabelMouseEntered
        
         logoutLabel.setForeground(new Color(0,102,102));
    }//GEN-LAST:event_logoutLabelMouseEntered

    private void logoutLabelMouseExited(MouseEvent evt) {//GEN-FIRST:event_logoutLabelMouseExited
        
         logoutLabel.setForeground(new Color(250,250,250));
    }//GEN-LAST:event_logoutLabelMouseExited

    private void logoutLabelMousePressed(MouseEvent evt) {//GEN-FIRST:event_logoutLabelMousePressed
       
        logoutLabel.setForeground(new Color(0,51,51));
    }//GEN-LAST:event_logoutLabelMousePressed
    
    /**
     * When logout button is clicked, ask for confirmation if the guest wants to
     * logout. If yes, proceed to login, if no, remain in this frame.
     */
    private void logoutLabelMouseReleased(MouseEvent evt) {//GEN-FIRST:event_logoutLabelMouseReleased
        //switch login frame
        int status=0;
        
        //show dialog box for confirmation (status = 0 - yes, 1 - no)
        status = JOptionPane.showConfirmDialog(jPanel2, "Do you really want to logout?", 
                "Logout", JOptionPane.YES_NO_OPTION);
        
        System.out.println("status: " + status);
        
        if(status == 0){
            LoginFrame login = null;
            login = new LoginFrame();
            login.displaylogin();
            this.setVisible(false);
            this.dispose();
        }else{
            // do nothing
        }
    }//GEN-LAST:event_logoutLabelMouseReleased
   
    private void exitButtonMouseEntered(MouseEvent evt) {//GEN-FIRST:event_exitButtonMouseEntered
        ImageIcon extbot = new ImageIcon(getClass().getResource("/img/x_focus.png"));
        exitButton.setIcon(extbot);
    }//GEN-LAST:event_exitButtonMouseEntered

    private void exitButtonMouseExited(MouseEvent evt) {//GEN-FIRST:event_exitButtonMouseExited
        ImageIcon extbot = new ImageIcon(getClass().getResource("/img/x_default.png"));
        exitButton.setIcon(extbot);
    }//GEN-LAST:event_exitButtonMouseExited

    private void exitButtonMousePressed(MouseEvent evt) {//GEN-FIRST:event_exitButtonMousePressed
        ImageIcon extbot = new ImageIcon(getClass().getResource("/img/x_clicked.png"));
        exitButton.setIcon(extbot);
    }//GEN-LAST:event_exitButtonMousePressed

    private void exitButtonMouseReleased(MouseEvent evt) {//GEN-FIRST:event_exitButtonMouseReleased
        int status=0; //holds the result status of the confirmation 
        
        //show dialog box for confirmation (status = 0 - yes, 1 - no)
        status = JOptionPane.showConfirmDialog(jPanel1, "Do you really want to exit?", 
                "Exit", JOptionPane.YES_NO_OPTION);
        
        if(status == 0){    //if status is yes
            database.extConnection(); //close database connection
            System.out.println("status: " + status);
            this.setDefaultCloseOperation(this.EXIT_ON_CLOSE);
            System.exit(0);
        }else{
            //do nothing
        }
    }//GEN-LAST:event_exitButtonMouseReleased
    public void dispFrame() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuestOptionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuestOptionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuestOptionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuestOptionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuestOptionFrame().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JPanel TopPanel;
    private JLabel WelcomGuestLabel;
    private JLabel exitButton;
    private JLabel jLabel2;
    private JLabel jLabel3;
    private JLabel jLabel4;
    private JLabel jLabel5;
    private JPanel jPanel1;
    private JPanel jPanel2;
    private JPanel jPanel3;
    private JLabel logoutLabel;
    private JButton manageAccountButton;
    private JButton reserveRoomsButton;
    // End of variables declaration//GEN-END:variables
}
