
package hotelreserve;

import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import static java.lang.Integer.parseInt;
import java.sql.SQLException;
import javax.swing.JOptionPane;


public class LoginFrame extends javax.swing.JFrame {
    
    private String roomPref;
    private boolean loginFlag = false;
    private Client[] presentGuest;
    private Hotel database = new Hotel();
    private int xMouse, yMouse;
    private String fname, lname, mname,bmonth, bday,byear, mobileNum, email; 
    private int accountID; 
    
    /**
     * Creates new form LoginFrame
     */
    
    public LoginFrame(){
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        welcomeLabel = new javax.swing.JLabel();
        AccountNameField = new javax.swing.JTextField();
        PasswordField = new javax.swing.JPasswordField();
        loginButton = new javax.swing.JButton();
        bigLogo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        fnameLabel = new javax.swing.JLabel();
        lnameLabel = new javax.swing.JLabel();
        mNameLabel = new javax.swing.JLabel();
        mobileNumLabel = new javax.swing.JLabel();
        BdayLabel = new javax.swing.JLabel();
        fnameTextField = new javax.swing.JTextField();
        lnameTextField = new javax.swing.JTextField();
        mnameTextField = new javax.swing.JTextField();
        mobileNumTextField = new javax.swing.JTextField();
        signUpLabel = new javax.swing.JLabel();
        sentence1Label = new javax.swing.JLabel();
        sentence2Label = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        birthMonthComboBox = new javax.swing.JComboBox();
        birthDayComboBox = new javax.swing.JComboBox();
        birthYearComboBox = new javax.swing.JComboBox();
        registerButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        exitButton = new javax.swing.JButton();
        pogressLabel = new javax.swing.JLabel();
        logiMini = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(200, 100));
        setUndecorated(true);
        setOpacity(0.0F);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(65, 64, 75));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(51, 51, 51));
        jPanel2.setMaximumSize(new java.awt.Dimension(600, 600));
        jPanel2.setPreferredSize(new java.awt.Dimension(600, 425));

        welcomeLabel.setFont(new java.awt.Font("Trajan Pro", 0, 20)); // NOI18N
        welcomeLabel.setForeground(new java.awt.Color(51, 51, 51));
        welcomeLabel.setText("WELCOME");

        AccountNameField.setFont(new java.awt.Font("Swis721 LtEx BT", 0, 14)); // NOI18N
        AccountNameField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        AccountNameField.setToolTipText("Account Last Name");

        PasswordField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        PasswordField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PasswordField.setToolTipText("Account ID number (6 - digit)");

        loginButton.setBackground(new java.awt.Color(0, 102, 102));
        loginButton.setFont(new java.awt.Font("Swis721 LtEx BT", 0, 14)); // NOI18N
        loginButton.setForeground(new java.awt.Color(255, 255, 255));
        loginButton.setText("Login");
        loginButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        bigLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/midtown2.png"))); // NOI18N
        bigLogo.setMaximumSize(new java.awt.Dimension(150, 150));
        bigLogo.setMinimumSize(new java.awt.Dimension(150, 150));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        fnameLabel.setFont(new java.awt.Font("Swis721 LtEx BT", 0, 14)); // NOI18N
        fnameLabel.setForeground(new java.awt.Color(51, 51, 51));
        fnameLabel.setText("First Name: ");

        lnameLabel.setFont(new java.awt.Font("Swis721 LtEx BT", 0, 14)); // NOI18N
        lnameLabel.setForeground(new java.awt.Color(51, 51, 51));
        lnameLabel.setText("Last Name: ");

        mNameLabel.setFont(new java.awt.Font("Swis721 LtEx BT", 0, 14)); // NOI18N
        mNameLabel.setForeground(new java.awt.Color(51, 51, 51));
        mNameLabel.setText("Middle Name: ");

        mobileNumLabel.setFont(new java.awt.Font("Swis721 LtEx BT", 0, 14)); // NOI18N
        mobileNumLabel.setForeground(new java.awt.Color(51, 51, 51));
        mobileNumLabel.setText("Mobile Number:");

        BdayLabel.setFont(new java.awt.Font("Swis721 LtEx BT", 0, 14)); // NOI18N
        BdayLabel.setForeground(new java.awt.Color(51, 51, 51));
        BdayLabel.setText("Birth Date:");

        fnameTextField.setToolTipText("Enter your first name");

        lnameTextField.setToolTipText("Enter your last name");

        mnameTextField.setToolTipText("Enter your middle name");

        mobileNumTextField.setToolTipText("Enter your mobile number");

        signUpLabel.setFont(new java.awt.Font("Trajan Pro", 0, 18)); // NOI18N
        signUpLabel.setForeground(new java.awt.Color(51, 51, 51));
        signUpLabel.setText("Sign UP: ");

        sentence1Label.setFont(new java.awt.Font("Swis721 LtEx BT", 0, 10)); // NOI18N
        sentence1Label.setForeground(new java.awt.Color(102, 102, 102));
        sentence1Label.setText("Fill the information below and have your own ");

        sentence2Label.setFont(new java.awt.Font("Swis721 LtEx BT", 0, 10)); // NOI18N
        sentence2Label.setForeground(new java.awt.Color(102, 102, 102));
        sentence2Label.setText("own account in MidTown Hotel for FREE.");

        emailLabel.setFont(new java.awt.Font("Swis721 LtEx BT", 0, 14)); // NOI18N
        emailLabel.setForeground(new java.awt.Color(51, 51, 51));
        emailLabel.setText("Email:");

        emailTextField.setToolTipText("Enter your email address");

        jLabel1.setFont(new java.awt.Font("Swis721 LtEx BT", 0, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Please login to your account using your last name and account ID");

        birthMonthComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Month", "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        birthMonthComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                birthMonthComboBoxActionPerformed(evt);
            }
        });

        birthDayComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Day", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30" }));

        birthYearComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Year", "2000", "1999", "1998", "1997", "1996", "1995", "1994", "1993", "1992", "1991", "1990", "1989", "1988", "1987", "1986", "1985", "1984", "1983", "1982", "1981", "1980" }));

        registerButton.setBackground(new java.awt.Color(0, 102, 153));
        registerButton.setFont(new java.awt.Font("Swis721 LtEx BT", 0, 14)); // NOI18N
        registerButton.setForeground(new java.awt.Color(255, 255, 255));
        registerButton.setText("Register");
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(bigLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(118, 118, 118))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(welcomeLabel)
                                .addGap(159, 159, 159))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(AccountNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(125, 125, 125))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(178, 178, 178))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(28, 28, 28)))))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(signUpLabel)
                                    .addComponent(sentence2Label)
                                    .addComponent(sentence1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lnameLabel)
                                            .addComponent(fnameLabel))
                                        .addGap(35, 35, 35)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lnameTextField)
                                            .addComponent(fnameTextField)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(mNameLabel)
                                        .addGap(18, 18, 18)
                                        .addComponent(mnameTextField))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(emailLabel)
                                        .addGap(85, 85, 85)
                                        .addComponent(emailTextField))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(mobileNumLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(mobileNumTextField))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(BdayLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(birthMonthComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(2, 2, 2)
                                        .addComponent(birthDayComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(2, 2, 2)
                                        .addComponent(birthYearComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(47, 47, 47))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(registerButton)
                        .addGap(86, 86, 86))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(signUpLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sentence1Label)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(sentence2Label)
                            .addGap(33, 33, 33)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(fnameLabel)
                                .addComponent(fnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lnameLabel)
                                .addComponent(lnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(mNameLabel)
                                .addComponent(mnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(BdayLabel)
                                    .addComponent(birthMonthComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(birthYearComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(birthDayComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(11, 11, 11)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(mobileNumLabel)
                                .addComponent(mobileNumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(11, 11, 11)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(emailLabel)
                                .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(23, 23, 23)
                            .addComponent(registerButton))
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(bigLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(welcomeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(AccountNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(loginButton)))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(65, 64, 75));
        jPanel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel3MouseDragged(evt);
            }
        });
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel3MousePressed(evt);
            }
        });

        exitButton.setBackground(new java.awt.Color(255, 255, 255));
        exitButton.setFont(new java.awt.Font("Swis721 LtEx BT", 0, 10)); // NOI18N
        exitButton.setForeground(new java.awt.Color(255, 0, 0));
        exitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/x_default.png"))); // NOI18N
        exitButton.setBorder(null);
        exitButton.setContentAreaFilled(false);
        exitButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitButton.setMargin(new java.awt.Insets(5, 14, 5, 14));
        exitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitButtonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                exitButtonMousePressed(evt);
            }
        });
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        pogressLabel.setFont(new java.awt.Font("Trajan Pro", 0, 16)); // NOI18N
        pogressLabel.setForeground(new java.awt.Color(255, 255, 255));
        pogressLabel.setText("LOGIN");

        logiMini.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/midtown2mini.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(logiMini)
                .addGap(18, 18, 18)
                .addComponent(pogressLabel)
                .addGap(687, 687, 687)
                .addComponent(exitButton))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logiMini)
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(pogressLabel))
                    .addComponent(exitButton))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("MIDTOWN HOTEL ONLINE RESERVATION SYSTEM © 2015 ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 870, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /* LOGIN PRESSED
      when the login button is pressed, check the Account name and password
      if it matches in one of the valid user.
    */
    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        
        try{
            loginFlag = database.checkLogin(AccountNameField.getText(), parseInt(PasswordField.getText()));
        if(loginFlag){
            System.out.println("Login successful");
            GuestOptionFrame guestOption = new GuestOptionFrame();
            guestOption.dispFrame();
            this.setVisible(false);
            this.dispose();
        }else{
            System.out.println("incorrect password");
        }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Please fill with your last name and account ID.");
        }
    }//GEN-LAST:event_loginButtonActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            database.getDataFromFile(); // call to retrieve the data from file
        } catch (SQLException ex) {
            Logger.getLogger(LoginFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        //fading effect
        for(double i=0.0;i<1.0;i=i+0.1){
            String val = i+"F";
            float f = Float.valueOf(val);
            this.setOpacity(f);
            try{
                Thread.sleep(20);
            }catch(Exception e){
            
            }
        }
         
    }//GEN-LAST:event_formWindowOpened

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed

        int status=0; //holds the result status of the confirmation 
        
        status = JOptionPane.showConfirmDialog(jPanel2, "Do you really want to exit?", 
                "Exit", JOptionPane.YES_NO_OPTION);
        
        if(status == 0){    //if status is yes
            database.extConnection(); //close database connection
            System.out.println("status: " + status);
            this.setDefaultCloseOperation(this.EXIT_ON_CLOSE);
            System.exit(0);
        }else{
            //do nothing
        }
    }//GEN-LAST:event_exitButtonActionPerformed

    private void exitButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonMouseEntered
        
        ImageIcon extbot = new ImageIcon(getClass().getResource("/img/x_focus.png"));
        exitButton.setIcon(extbot);
    }//GEN-LAST:event_exitButtonMouseEntered

    private void exitButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonMouseExited
        
        ImageIcon extbot = new ImageIcon(getClass().getResource("/img/x_default.png"));
        exitButton.setIcon(extbot);
        
    }//GEN-LAST:event_exitButtonMouseExited

    private void exitButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonMousePressed
        
        ImageIcon extbot = new ImageIcon(getClass().getResource("/img/x_clicked.png"));
        exitButton.setIcon(extbot);
    }//GEN-LAST:event_exitButtonMousePressed

    /**
     * This will add days and remove days based on month selected
     */
    private void birthMonthComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_birthMonthComboBoxActionPerformed

        switch((String)birthMonthComboBox.getSelectedItem()){
            
        //Add day
        case "January":   case "March": 
        case "May":       case "July":   
        case "September": case "November":
            
            if(birthDayComboBox.getItemCount() == 29){
                System.out.println("dayCount: " +birthDayComboBox.getItemCount());
                birthDayComboBox.addItem("29");
                
            }
            if(birthDayComboBox.getItemCount() == 30){
                System.out.println("dayCount: " +birthDayComboBox.getItemCount());
                birthDayComboBox.addItem("30");
                
            }
            if(birthDayComboBox.getItemCount() == 31){
                System.out.println("dayCount: " +birthDayComboBox.getItemCount());
                birthDayComboBox.addItem("31");
                
            }
            break;
        //Remove days;    
        case "February":
            if(birthDayComboBox.getItemCount() == 32){
                birthDayComboBox.removeItemAt(31);
            }
            if(birthDayComboBox.getItemCount() == 31){
                birthDayComboBox.removeItemAt(30);
            }

            break;
            
        //Remove day 31
        case "April":   case "June":
        case "August":  case "October":
        case "December":
            if(birthDayComboBox.getItemCount() == 32){
               birthDayComboBox.removeItem("31");
               System.out.println("dayCount: " +birthDayComboBox.getItemCount());
            }else{ 
                // do nothing
            }
            break;
        default:
            break;
        }
    }//GEN-LAST:event_birthMonthComboBoxActionPerformed

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed

        // check if all fields in Registration are filled
        if(checkRegistration()){
            signup();
            this.setVisible(false);
            this.dispose();
        }
    }//GEN-LAST:event_registerButtonActionPerformed

    private void jPanel3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        this.setLocation(x-xMouse,y-yMouse);
    }//GEN-LAST:event_jPanel3MouseDragged

    private void jPanel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MousePressed

        xMouse = evt.getX();
        yMouse = evt.getY();
        
    }//GEN-LAST:event_jPanel3MousePressed

    /**
     * @param args the command line arguments
     */
    public void displaylogin(){
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            new LoginFrame().setVisible(true);
                
            }
        });
    }
    
    /*
        This method will get all the information from the registration 
        text fields for the creation a new guest. Account pin or ID of the 
        guest is also generated here which is a 6 - digit random number code.
    */
    public void signup(){ 
         boolean isIDvalid = true; 
        
         presentGuest = new Client[database.getGuestCounter()]; // set size of the Client array using guestCounter 
         presentGuest  = database.getAllGuest();    //presentGuest points to all guest 
         System.out.println("Loading file...");
         
         //Get the information from the textFields
         fname = fnameTextField.getText();
         mname = mnameTextField.getText();
         lname = lnameTextField.getText();
         bmonth = (String) birthMonthComboBox.getSelectedItem();
         bday   = (String) birthDayComboBox.getSelectedItem(); 
         byear  = (String) birthYearComboBox.getSelectedItem();
         mobileNum = mobileNumTextField.getText();
         email = emailTextField.getText();
         roomPref = "none";
         
         do{
         //generate account pin/ID number
            for(int i=0;i<database.getGuestCounter();i++){
               //generate random number of 6 - digit
               do{
                   accountID = (int) (Math.random() *1000000);
               }while(accountID<100000);
               
               //check if accountID is already present
               if(accountID == presentGuest[i].getAccountID()){
                  isIDvalid = false;
               }

            }
        }while(!isIDvalid);
           
        System.out.println(accountID + " " + fname + " " + mname + " " + 
                        lname + " " + bday + " " + mobileNum + " " + email+"\n");

        RegisterConfirmFrame confirm = new RegisterConfirmFrame();
            
        confirm.displayFrame();
        confirm.setNewGuest(accountID,fname,mname,lname,bmonth,bday,byear,mobileNum,email);

        //reset the registration text fields
        fnameTextField.setText("");
        mnameTextField.setText("");
        lnameTextField.setText("");
        birthMonthComboBox.setSelectedIndex(1);
        birthDayComboBox.setSelectedIndex(1);
        birthYearComboBox.setSelectedIndex(1);
        mobileNumTextField.setText("");
        emailTextField.setText("");
    }
    
    
    /*
        This method will check if all registration textfields are filled 
        with information. If the field is empty, change the label to RED,
        if the field is supplied with information, change the label
        color to BLACK.
    */
    public boolean checkRegistration(){
        boolean registrationValid = true;
        
        if(fnameTextField.getText().isEmpty()){
             registrationValid = false;
             fnameLabel.setForeground(Color.red);
        }else{
             fnameLabel.setForeground(Color.black);
        }
        
        if(lnameTextField.getText().isEmpty()){
             registrationValid = false;
             lnameLabel.setForeground(Color.red);
        }else{
             lnameLabel.setForeground(Color.black);
        }
        
        if(mnameTextField.getText().isEmpty()){
             registrationValid = false;
             mNameLabel.setForeground(Color.red);
        }else{
             mNameLabel.setForeground(Color.black);
        }
        
        if(emailTextField.getText().isEmpty()){
             registrationValid = false;
             emailLabel.setForeground(Color.red);
        }else{
             emailLabel.setForeground(Color.black);
        }
        
        if(mobileNumTextField.getText().isEmpty()){
             registrationValid = false;
             mobileNumLabel.setForeground(Color.red);
        }else{
             mobileNumLabel.setForeground(Color.black);
        }
        if(birthMonthComboBox.getSelectedItem().equals("Month")){
             registrationValid = false;
             BdayLabel.setForeground(Color.red);
        }else{
             BdayLabel.setForeground(Color.black);
        }
        
        if(birthDayComboBox.getSelectedItem().equals("Day")){
             registrationValid = false;
             BdayLabel.setForeground(Color.red);
        }else{
             BdayLabel.setForeground(Color.black);
        }
        
        if(birthYearComboBox.getSelectedItem().equals("Year")){
             registrationValid = false;
             BdayLabel.setForeground(Color.red);
        }else{
             BdayLabel.setForeground(Color.black);
        }
        
        System.out.println("registrationValid: " + registrationValid);
        
        return registrationValid;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AccountNameField;
    private javax.swing.JLabel BdayLabel;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JLabel bigLogo;
    private javax.swing.JComboBox birthDayComboBox;
    private javax.swing.JComboBox birthMonthComboBox;
    private javax.swing.JComboBox birthYearComboBox;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel fnameLabel;
    private javax.swing.JTextField fnameTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lnameLabel;
    private javax.swing.JTextField lnameTextField;
    private javax.swing.JLabel logiMini;
    private javax.swing.JButton loginButton;
    private javax.swing.JLabel mNameLabel;
    private javax.swing.JTextField mnameTextField;
    private javax.swing.JLabel mobileNumLabel;
    private javax.swing.JTextField mobileNumTextField;
    private javax.swing.JLabel pogressLabel;
    private javax.swing.JButton registerButton;
    private javax.swing.JLabel sentence1Label;
    private javax.swing.JLabel sentence2Label;
    private javax.swing.JLabel signUpLabel;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
}
