
package hotelreserve;

import static java.lang.Integer.parseInt;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class ManageAccountsFrame extends javax.swing.JFrame {
    private Hotel database = new Hotel();
    private Room[] myRooms = new Room[50];
    private Client guest = new Client();
    private int xMouse, yMouse, roomCounter, roomCanceledCount;
    private Room[] roomNums = new Room[20];
    private int[] canceledRoom = new int[20];
    

    public ManageAccountsFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        guestAccounttxtLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        reservationtxtLabel = new javax.swing.JLabel();
        firstNameLabel = new javax.swing.JLabel();
        midNameLabel = new javax.swing.JLabel();
        lastNameLabel = new javax.swing.JLabel();
        birthdateLabel = new javax.swing.JLabel();
        mobileLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        reservationTable = new javax.swing.JTable();
        cencelSelectionButton = new javax.swing.JButton();
        canceledRoomLabel = new javax.swing.JLabel();
        canceledRoomResults = new javax.swing.JLabel();
        undoButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        topPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        exitButton = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(150, 100));
        setUndecorated(true);
        setOpacity(0.0F);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(65, 64, 75));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(51, 51, 51));

        jLabel3.setFont(new java.awt.Font("Swis721 LtEx BT", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("First Name: ");

        guestAccounttxtLabel.setFont(new java.awt.Font("Swis721 LtEx BT", 0, 20)); // NOI18N
        guestAccounttxtLabel.setText("Guest Account");

        jLabel5.setFont(new java.awt.Font("Swis721 LtEx BT", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Middle Name: ");

        jLabel6.setFont(new java.awt.Font("Swis721 LtEx BT", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Last Name: ");

        jLabel7.setFont(new java.awt.Font("Swis721 LtEx BT", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("BirthDate: ");

        jLabel8.setFont(new java.awt.Font("Swis721 LtEx BT", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Email: ");

        jLabel9.setFont(new java.awt.Font("Swis721 LtEx BT", 0, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Mobile #: ");

        reservationtxtLabel.setFont(new java.awt.Font("Swis721 LtEx BT", 0, 20)); // NOI18N
        reservationtxtLabel.setText("Reservations:");

        firstNameLabel.setFont(new java.awt.Font("Swis721 LtEx BT", 0, 14)); // NOI18N
        firstNameLabel.setText("First Name");

        midNameLabel.setFont(new java.awt.Font("Swis721 LtEx BT", 0, 14)); // NOI18N
        midNameLabel.setText("First Name");

        lastNameLabel.setFont(new java.awt.Font("Swis721 LtEx BT", 0, 14)); // NOI18N
        lastNameLabel.setText("First Name");

        birthdateLabel.setFont(new java.awt.Font("Swis721 LtEx BT", 0, 14)); // NOI18N
        birthdateLabel.setText("First Name");

        mobileLabel.setFont(new java.awt.Font("Swis721 LtEx BT", 0, 14)); // NOI18N
        mobileLabel.setText("First Name");

        emailLabel.setFont(new java.awt.Font("Swis721 LtEx BT", 0, 14)); // NOI18N
        emailLabel.setText("First Name");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Note: Cancellation of room reservations are cannot be undone and payments are not refunded.");

        reservationTable.setFont(new java.awt.Font("Swis721 LtEx BT", 0, 15)); // NOI18N
        reservationTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Room #", "Room Type", "Start Date", "End Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        reservationTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        reservationTable.setGridColor(new java.awt.Color(255, 255, 255));
        reservationTable.setRowHeight(25);
        reservationTable.setSelectionBackground(new java.awt.Color(0, 102, 102));
        reservationTable.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        jScrollPane1.setViewportView(reservationTable);
        reservationTable.getAccessibleContext().setAccessibleDescription("");

        cencelSelectionButton.setBackground(new java.awt.Color(204, 51, 0));
        cencelSelectionButton.setFont(new java.awt.Font("Swis721 LtEx BT", 0, 11)); // NOI18N
        cencelSelectionButton.setForeground(new java.awt.Color(255, 255, 255));
        cencelSelectionButton.setText("CANCEL RESERVATION");
        cencelSelectionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cencelSelectionButtonActionPerformed(evt);
            }
        });

        canceledRoomLabel.setFont(new java.awt.Font("Swis721 LtEx BT", 0, 16)); // NOI18N
        canceledRoomLabel.setForeground(new java.awt.Color(51, 51, 51));
        canceledRoomLabel.setText("Canceled Room:");

        canceledRoomResults.setFont(new java.awt.Font("Swis721 LtEx BT", 0, 14)); // NOI18N
        canceledRoomResults.setText("result");

        undoButton.setBackground(new java.awt.Color(0, 102, 153));
        undoButton.setFont(new java.awt.Font("Swis721 LtEx BT", 0, 11)); // NOI18N
        undoButton.setForeground(new java.awt.Color(255, 255, 255));
        undoButton.setText("UNDO");
        undoButton.setEnabled(false);
        undoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                undoButtonActionPerformed(evt);
            }
        });

        saveButton.setBackground(new java.awt.Color(0, 102, 204));
        saveButton.setFont(new java.awt.Font("Swis721 LtEx BT", 0, 11)); // NOI18N
        saveButton.setForeground(new java.awt.Color(255, 255, 255));
        saveButton.setText("SAVE");
        saveButton.setEnabled(false);
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 575, Short.MAX_VALUE)
                    .addComponent(jSeparator1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(guestAccounttxtLabel)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(firstNameLabel)
                            .addComponent(midNameLabel)
                            .addComponent(lastNameLabel))
                        .addGap(79, 79, 79)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(birthdateLabel)
                            .addComponent(mobileLabel)
                            .addComponent(emailLabel)))
                    .addComponent(reservationtxtLabel)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(canceledRoomLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(canceledRoomResults)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(cencelSelectionButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(undoButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(saveButton))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(guestAccounttxtLabel)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7)
                            .addComponent(firstNameLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel9)
                            .addComponent(midNameLabel)
                            .addComponent(mobileLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addComponent(lastNameLabel)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(birthdateLabel)
                        .addGap(47, 47, 47)
                        .addComponent(emailLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(reservationtxtLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(canceledRoomLabel)
                    .addComponent(canceledRoomResults))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cencelSelectionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(undoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        topPanel.setBackground(new java.awt.Color(65, 64, 75));
        topPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                topPanelMouseDragged(evt);
            }
        });
        topPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                topPanelMousePressed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/midtown2mini.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Trajan Pro", 0, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Manage account");

        backButton.setBackground(new java.awt.Color(0, 102, 102));
        backButton.setFont(new java.awt.Font("Swis721 LtEx BT", 0, 11)); // NOI18N
        backButton.setForeground(new java.awt.Color(255, 255, 255));
        backButton.setText("BACK");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        exitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/x_default.png"))); // NOI18N
        exitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitButtonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                exitButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                exitButtonMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
        topPanel.setLayout(topPanelLayout);
        topPanelLayout.setHorizontalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(topPanelLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(backButton)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(exitButton))))
        );
        topPanelLayout.setVerticalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(31, 31, 31))
            .addGroup(topPanelLayout.createSequentialGroup()
                .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(topPanelLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topPanelLayout.createSequentialGroup()
                        .addComponent(exitButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(backButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setText("MIDTOWN HOTEL ONLINE RESERVATION SYSTEM © 2015 ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(topPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(231, 231, 231)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(topPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel4)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        //fading in effect
        System.out.println("Guest name: "+guest.getName());
         for(double i=0.0;i<1.0;i=i+0.1){
            String val = i+"F";
            float f = Float.valueOf(val);
            this.setOpacity(f);
            try{
                Thread.sleep(20);
            }catch(Exception e){
            
            }
        }
         
        roomCanceledCount = 0; //reset room canceled counter
        System.out.println("\nGuest Account Frame"); 
        displayReservedRooms();     //display rooms reserved by the guest
        
    }//GEN-LAST:event_formWindowOpened

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        
        GuestOptionFrame option = new GuestOptionFrame();
        option.dispFrame();
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_backButtonActionPerformed
    
    private void topPanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_topPanelMouseDragged
        
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xMouse,y-yMouse);
    }//GEN-LAST:event_topPanelMouseDragged

    private void topPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_topPanelMousePressed
        
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_topPanelMousePressed
    
    /**
     * When save button is clicked, It will verify if the guest really want to cancel
     * the room reservations and ask for the guest account ID. If the ID is valid 
     * it will cancel all selected room reservation. 
     */
    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        int status=0;
        int guestID;
        try{
        //show dialog box for confirmation
            status = JOptionPane.showConfirmDialog(jPanel2, "Do you really want to cancel reservations?", 
                    "Save changes", JOptionPane.YES_NO_OPTION);
        
            System.out.println("status: " + status);
        
        if(status == 0){
            
            guestID = parseInt(JOptionPane.showInputDialog(jPanel1, "Enter your account ID:"));
            
            if(database.verifyGuest(guestID)){  
                saveCanceledReservations(); // call to cancel room resrvation
                try {
                    //updates the changes in reservation in the database
                    database.updateRoomChanges_DB();
                } catch (SQLException ex) {
                    Logger.getLogger(ManageAccountsFrame.class.getName()).log(Level.SEVERE, null, ex);
                }

                GuestOptionFrame option = new GuestOptionFrame();
                option.dispFrame();
                this.setVisible(false);

                JOptionPane.showMessageDialog(jPanel1, "You have successfully cancelled your reservations. ");

                System.out.println("Save changes in reservation.");
                roomCanceledCount= 0;
                
                this.dispose();
            }else{
                JOptionPane.showMessageDialog(jPanel1, "Invalid Account ID. ");
            }
        }else if(status == 1){
            System.out.println("no changes in reservation.");
        }else{
            System.out.println("canceled changes in reservation.");
        }
        
        }catch(Exception e){ 
            JOptionPane.showMessageDialog(jPanel1, "Error saving changes. Please contact "
                    + "the technical support to solve this problem. ");
        }
        
    }//GEN-LAST:event_saveButtonActionPerformed

    private void cencelSelectionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cencelSelectionButtonActionPerformed
        String result = " ";
        int temp;
        boolean isAlreadySelected = false;
        
        try{
            int selectedRow = reservationTable.getSelectedRow();

            //Check for duplicate, if true, do not add in the canceled rooms
            temp = (int) reservationTable.getValueAt(selectedRow,0);
            for(int i=0;i<roomCanceledCount;i++){
                if(temp == canceledRoom[i]){
                    isAlreadySelected = true;
                }
            }

            if(!isAlreadySelected){
                canceledRoom[roomCanceledCount] = (int) reservationTable.getValueAt(selectedRow,0);
                System.out.println("Canceled room: " + canceledRoom[roomCanceledCount]);
                roomCanceledCount++;

                for(int i=0;i<roomCanceledCount;i++){
                    result += canceledRoom[i]+",";
                }


                canceledRoomResults.setText(result);
                System.out.println(result);
                updateSaveButton();
            }else{
                System.out.println(temp + " is already selected. ");
                JOptionPane.showMessageDialog(jPanel1, "Room "+temp + " is already selected. ");
            }
        }catch(Exception e){
            System.out.println("Error occured. No row is selected");
        }
    }//GEN-LAST:event_cencelSelectionButtonActionPerformed

    private void undoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_undoButtonActionPerformed
        String result = " ";
        if(roomCanceledCount > 0){
            roomCanceledCount--;
            canceledRoom[roomCanceledCount] = 0;

            for(int i=0;i<roomCanceledCount;i++){
                result += canceledRoom[i]+",";
            }
            canceledRoomResults.setText(result);
            System.out.println(result);
            updateSaveButton();
        }
        
    }//GEN-LAST:event_undoButtonActionPerformed
               
    private void exitButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonMouseEntered
        ImageIcon extbot = new ImageIcon(getClass().getResource("/img/x_focus.png"));
        exitButton.setIcon(extbot);
    }//GEN-LAST:event_exitButtonMouseEntered

    private void exitButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonMouseExited
        ImageIcon extbot = new ImageIcon(getClass().getResource("/img/x_default.png"));
        exitButton.setIcon(extbot);
    }//GEN-LAST:event_exitButtonMouseExited

    private void exitButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonMousePressed
        ImageIcon extbot = new ImageIcon(getClass().getResource("/img/x_clicked.png"));
        exitButton.setIcon(extbot);
    }//GEN-LAST:event_exitButtonMousePressed

    private void exitButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonMouseReleased
          int status=0; //holds the result status of the confirmation 
        
        //show dialog box for confirmation (status = 0 - yes, 1 - no)
        status = JOptionPane.showConfirmDialog(jPanel1, "Do you really want to exit?", 
                "Exit", JOptionPane.YES_NO_OPTION);
        
        if(status == 0){    //if status is yes
            database.extConnection(); //close database connection
            System.out.println("status: " + status);
            this.setDefaultCloseOperation(this.EXIT_ON_CLOSE);
            System.exit(0);
        }else{
            //do nothing
        }
    }//GEN-LAST:event_exitButtonMouseReleased

    public  void displayFrame() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageAccountsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageAccountsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageAccountsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageAccountsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageAccountsFrame().setVisible(true);
            }
        });
    }
    
    /**
     * This will display all the reserved rooms by the guest 
     */
    public void displayReservedRooms(){
        
        guest = database.getGuest();
        
        firstNameLabel.setText(guest.getfName());
        lastNameLabel.setText(guest.getName());
        midNameLabel.setText(guest.getMName());
        birthdateLabel.setText(guest.getBday());
        mobileLabel.setText(guest.getMobileNum());
        emailLabel.setText(guest.getEmail());
        
        getMyRooms();
        
        //table
        int data1    = 0;
        String data2 = "none";
        String data3 = "none";
        String data4 = "none";
        DefaultTableModel model = (DefaultTableModel) reservationTable.getModel();
    
        for(int i=0;i<roomCounter;i++){
            data1 = roomNums[i].getRoomNum();
            data2 = roomNums[i].getRoomType();
            data3 = roomNums[i].getStartDate();
            data4 = roomNums[i].getEndDate();
            Object[] rows = { data1, data2, data3, data4 };
            
            model.addRow(rows);
        }
        
    }
    
    /**
     * THis will get the rooms reserved by the guest and transfer it to
     * the myRooms array.
     */
    public void getMyRooms(){
        myRooms = database.getGuestRooms();
        roomCounter = 0;
        
        for(int i=0;i<database.getRoomCounter();i++){
            if(guest.getAccountID() == myRooms[i].getOccupantID() ){
                roomNums[roomCounter] = myRooms[i]; //get the room number of guest
                roomCounter++;
            }
        }
    }
    
    /**
     * This will check if there is canceled reservation. If yes, allow
     * the save button to be clicked, if not disable the save button.
     */
    public void updateSaveButton(){
        if(roomCanceledCount>0){
            saveButton.setEnabled(true);
            undoButton.setEnabled(true);
        }else{
            saveButton.setEnabled(false);
            undoButton.setEnabled(false);
            canceledRoomResults.setText("none");
        }
    }
    
    public void saveCanceledReservations(){
        for(int i=0;i<roomCanceledCount;i++){   //canceled reservation loop
            for(int i2=0;i2<roomCounter;i2++){  //all selected rooms loop
                if(canceledRoom[i] == roomNums[i2].getRoomNum()){
                    roomNums[i2].setAvailability(true);
                    roomNums[i2].setOccupant("none");
                    roomNums[i2].setOccupantID(0);
                    roomNums[i2].setStartDate("none");
                    roomNums[i2].setEndDate("none");
                }
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel birthdateLabel;
    private javax.swing.JLabel canceledRoomLabel;
    private javax.swing.JLabel canceledRoomResults;
    private javax.swing.JButton cencelSelectionButton;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel exitButton;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JLabel guestAccounttxtLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JLabel midNameLabel;
    private javax.swing.JLabel mobileLabel;
    private javax.swing.JTable reservationTable;
    private javax.swing.JLabel reservationtxtLabel;
    private javax.swing.JButton saveButton;
    private javax.swing.JPanel topPanel;
    private javax.swing.JButton undoButton;
    // End of variables declaration//GEN-END:variables
}
