
package hotelreserve;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class PaymentFrame extends javax.swing.JFrame {
    private Hotel database = new Hotel();
    private int xMouse, yMouse;

    public PaymentFrame() {
        initComponents();
    }

    /*
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        GuestLabel = new javax.swing.JLabel();
        GuestNameResult = new javax.swing.JLabel();
        TransactionLabel = new javax.swing.JLabel();
        reservationLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        totalFeeLabel = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        totalFeeResult = new javax.swing.JLabel();
        PaymentLabel = new javax.swing.JLabel();
        OKButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        GuestLabel1 = new javax.swing.JLabel();
        stayDurationResult = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        searchResultTable = new javax.swing.JTable();
        creditCardPin = new javax.swing.JPasswordField();
        pinLabel1 = new javax.swing.JLabel();
        pinLabel2 = new javax.swing.JLabel();
        securitypin = new javax.swing.JPasswordField();
        topPanel = new javax.swing.JPanel();
        miniIcon = new javax.swing.JLabel();
        progressLabel = new javax.swing.JLabel();
        exitButton = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(300, 200));
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(65, 64, 75));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        GuestLabel.setFont(new java.awt.Font("Swis721 LtEx BT", 0, 15)); // NOI18N
        GuestLabel.setText("Guest: ");

        GuestNameResult.setFont(new java.awt.Font("Swis721 LtEx BT", 0, 15)); // NOI18N
        GuestNameResult.setText("Guest Name");

        TransactionLabel.setFont(new java.awt.Font("Swis721 LtEx BT", 0, 15)); // NOI18N
        TransactionLabel.setText("Transaction: ");

        reservationLabel.setFont(new java.awt.Font("Swis721 LtEx BT", 0, 15)); // NOI18N
        reservationLabel.setText("Hotel Room Reservation ");

        totalFeeLabel.setFont(new java.awt.Font("Swis721 LtEx BT", 0, 15)); // NOI18N
        totalFeeLabel.setText("Total Fee:");

        totalFeeResult.setFont(new java.awt.Font("Swis721 LtEx BT", 0, 15)); // NOI18N
        totalFeeResult.setText("0 php");

        PaymentLabel.setFont(new java.awt.Font("Swis721 LtEx BT", 0, 15)); // NOI18N
        PaymentLabel.setText("Payment Transaction:");

        OKButton.setBackground(new java.awt.Color(0, 102, 102));
        OKButton.setFont(new java.awt.Font("Swis721 LtEx BT", 0, 14)); // NOI18N
        OKButton.setForeground(new java.awt.Color(255, 255, 255));
        OKButton.setText("OK");
        OKButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        OKButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKButtonActionPerformed(evt);
            }
        });

        cancelButton.setBackground(new java.awt.Color(204, 51, 0));
        cancelButton.setFont(new java.awt.Font("Swis721 LtEx BT", 0, 14)); // NOI18N
        cancelButton.setForeground(new java.awt.Color(255, 255, 255));
        cancelButton.setText("Cancel");
        cancelButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        GuestLabel1.setFont(new java.awt.Font("Swis721 LtEx BT", 0, 15)); // NOI18N
        GuestLabel1.setText("Stay Duration: ");

        stayDurationResult.setFont(new java.awt.Font("Swis721 LtEx BT", 0, 15)); // NOI18N
        stayDurationResult.setText("result");

        searchResultTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "RoomNumber", "RoomType", "BedNumber", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(searchResultTable);

        creditCardPin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditCardPinActionPerformed(evt);
            }
        });

        pinLabel1.setFont(new java.awt.Font("Swis721 LtEx BT", 0, 15)); // NOI18N
        pinLabel1.setText("Credit Card Number: ");

        pinLabel2.setFont(new java.awt.Font("Swis721 LtEx BT", 0, 15)); // NOI18N
        pinLabel2.setText("Security pin:");

        securitypin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                securitypinActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(209, 209, 209)
                            .addComponent(OKButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(cancelButton))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(36, 36, 36)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(322, 322, 322)
                                    .addComponent(totalFeeLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(totalFeeResult))
                                .addComponent(PaymentLabel)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addGap(39, 39, 39)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                    .addComponent(TransactionLabel)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(reservationLabel)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 165, Short.MAX_VALUE))
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                    .addComponent(GuestLabel)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(GuestNameResult)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(GuestLabel1)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(stayDurationResult))))
                                        .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)))))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(63, 63, 63)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(pinLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(securitypin, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(54, 54, 54))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(pinLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(creditCardPin, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GuestLabel)
                    .addComponent(GuestNameResult)
                    .addComponent(GuestLabel1)
                    .addComponent(stayDurationResult))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TransactionLabel)
                    .addComponent(reservationLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalFeeLabel)
                    .addComponent(totalFeeResult))
                .addGap(1, 1, 1)
                .addComponent(PaymentLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(creditCardPin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pinLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(securitypin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pinLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OKButton)
                    .addComponent(cancelButton))
                .addGap(14, 14, 14))
        );

        topPanel.setBackground(new java.awt.Color(65, 64, 75));
        topPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                topPanelMouseDragged(evt);
            }
        });
        topPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                topPanelMousePressed(evt);
            }
        });

        miniIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/midtown2mini.png"))); // NOI18N
        miniIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        miniIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                miniIconMouseClicked(evt);
            }
        });

        progressLabel.setFont(new java.awt.Font("Trajan Pro", 0, 18)); // NOI18N
        progressLabel.setForeground(new java.awt.Color(255, 255, 255));
        progressLabel.setText("Payment Transaction");

        exitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/x_default.png"))); // NOI18N
        exitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitButtonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                exitButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                exitButtonMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
        topPanel.setLayout(topPanelLayout);
        topPanelLayout.setHorizontalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(miniIcon)
                .addGap(18, 18, 18)
                .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(topPanelLayout.createSequentialGroup()
                        .addComponent(progressLabel)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(exitButton))))
        );
        topPanelLayout.setVerticalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(miniIcon))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topPanelLayout.createSequentialGroup()
                .addComponent(exitButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(progressLabel)
                .addGap(14, 14, 14))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("MIDTOWN HOTEL ONLINE RESERVATION SYSTEM © 2015 ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(topPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(183, 183, 183)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(topPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(31, 31, 31))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        SearchResultFrame result = new SearchResultFrame();
        result.displayFrame();
        this.setVisible(false);
    }//GEN-LAST:event_cancelButtonActionPerformed

    /*
     * When ok button is clicked, first check if the pin textfield have values or
     * is not empty, if so, proceed to next frame.
     */
    private void OKButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKButtonActionPerformed
        //check if pin text field is filled
        if(checkPin()){
            ConfirmFrame confirm = new ConfirmFrame();
            confirm.displayFrame();
            this.setVisible(false);
            this.dispose();
            
            //call method to generate the confirmation code
            database.generateConfiramtionCode();
            
        }else{
            JOptionPane.showMessageDialog(jPanel2, "Please enter your credit card pin number.");
        }
    }//GEN-LAST:event_OKButtonActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
        System.out.println("\nPayment Transaction Window");
        
        //fading effect
        for(double i=0.0;i<1.0;i=i+0.1){
            String val = i+"F";
            float f = Float.valueOf(val);
            this.setOpacity(f);
            try{
                Thread.sleep(20);
            }catch(Exception e){
            
            }
        }
         
         // displays the search result in the panel
         displayResult(); 
         
    }//GEN-LAST:event_formWindowOpened

    private void topPanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_topPanelMouseDragged
       
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        this.setLocation(x-xMouse,y-yMouse);
    }//GEN-LAST:event_topPanelMouseDragged

    private void topPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_topPanelMousePressed
       
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_topPanelMousePressed

    private void miniIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miniIconMouseClicked
        
        int status=0; //holds the result status of the confirmation 
        
        //show dialog box for confirmation (status = 0 - yes, 1 - no)
        status = JOptionPane.showConfirmDialog(jPanel2, "Reservation process will be canceled. Do you wish to continue?", 
                "Warning", JOptionPane.YES_NO_OPTION);
        
        if(status == 0){    //if status is yes
            GuestOptionFrame option = new GuestOptionFrame();
            option.dispFrame();
            this.setVisible(false);
            this.dispose();
        }else{
            //do nothing
        }
    }//GEN-LAST:event_miniIconMouseClicked

    private void exitButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonMouseEntered
        ImageIcon extbot = new ImageIcon(getClass().getResource("/img/x_focus.png"));
        exitButton.setIcon(extbot);           
    }//GEN-LAST:event_exitButtonMouseEntered

    private void exitButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonMouseExited
        ImageIcon extbot = new ImageIcon(getClass().getResource("/img/x_default.png"));
        exitButton.setIcon(extbot);
    }//GEN-LAST:event_exitButtonMouseExited

    private void exitButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonMousePressed
         ImageIcon extbot = new ImageIcon(getClass().getResource("/img/x_clicked.png"));
        exitButton.setIcon(extbot);
    }//GEN-LAST:event_exitButtonMousePressed

    private void exitButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonMouseReleased
           
        int status=0; //holds the result status of the confirmation 
        
        //show dialog box for confirmation (status = 0 - yes, 1 - no)
        status = JOptionPane.showConfirmDialog(jPanel1, "Do you really want to exit?", 
                "Exit", JOptionPane.YES_NO_OPTION);
        
        if(status == 0){    //if status is yes
            database.extConnection(); //close database connection
            System.out.println("status: " + status);
            this.setDefaultCloseOperation(this.EXIT_ON_CLOSE);
            System.exit(0);
        }else{
            //do nothing
        }
    }//GEN-LAST:event_exitButtonMouseReleased

    private void creditCardPinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditCardPinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_creditCardPinActionPerformed

    private void securitypinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_securitypinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_securitypinActionPerformed
                   
   
    /**
     * @param args the command line arguments
     */
    public void displayFrame() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaymentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaymentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaymentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaymentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaymentFrame().setVisible(true);
            }
        });
        
    }
    
    
    /*
      This will display the search result in the table
      from the result array.
    */
    public void displayResult(){
        //display the total fee of reservation
        totalFeeResult.setText(Float.toString(database.calculateTotalFee())+" php");
        
        GuestNameResult.setText(database.getGuestName());
        stayDurationResult.setText(Integer.toString(database.getStayDuration()));
        
        int roomCounter = database.getSelectedRoomsCounter();
        int[] roomNums = new int[roomCounter];
        roomNums = database.getGuestSelRooms();
        
        System.out.println("roomCounter: "+roomCounter);
        
        int     data1 = 0;
        String  data2 = "none";
        int     data3 = 0;
        float   data4 = 0;
        
        DefaultTableModel model = (DefaultTableModel) searchResultTable.getModel();

        for(int i=0;i<roomCounter;i++){
            data1 = roomNums[i];
            data2 = database.getSelectedRoomType();
            data3 = database.getSelectedRoomBed();
            data4 = database.getSelectedRoomPrice();
            Object[] rows = { data1, data2, data3, data4 };
            model.addRow(rows);
            
        }
    }
    
    /**
     * Check if the pin text field is not empty.
     */
    public boolean checkPin(){
       boolean check = false;
       try{
            if(creditCardPin.getText().isEmpty()){
                check = false;
            }else{
                check = true;
            }
            
            if(securitypin.getText().isEmpty()){
                check = false;
            }else{
                check = true;
            }
            
       }catch(Exception e){}
        return check;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel GuestLabel;
    private javax.swing.JLabel GuestLabel1;
    private javax.swing.JLabel GuestNameResult;
    private javax.swing.JButton OKButton;
    private javax.swing.JLabel PaymentLabel;
    private javax.swing.JLabel TransactionLabel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JPasswordField creditCardPin;
    private javax.swing.JLabel exitButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel miniIcon;
    private javax.swing.JLabel pinLabel1;
    private javax.swing.JLabel pinLabel2;
    private javax.swing.JLabel progressLabel;
    private javax.swing.JLabel reservationLabel;
    private javax.swing.JTable searchResultTable;
    private javax.swing.JPasswordField securitypin;
    private javax.swing.JLabel stayDurationResult;
    private javax.swing.JPanel topPanel;
    private javax.swing.JLabel totalFeeLabel;
    private javax.swing.JLabel totalFeeResult;
    // End of variables declaration//GEN-END:variables
}
