
package hotelreserve;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class SearchResultFrame extends javax.swing.JFrame {
    private Hotel database = new Hotel();
    private int xMouse, yMouse;
    private int selectedRoomCount=0;
    private int[] guestSelectedRooms = database.getGuestSelRooms();
    private final int resultSize = 10;
    private int selectedRoomNum;

    public SearchResultFrame(){
        initComponents();
        searchResultTable.setDragEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        roomNoLabel = new javax.swing.JLabel();
        paymentButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        roomPictureLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        searchResultTable = new javax.swing.JTable();
        reserveButton = new javax.swing.JButton();
        undoButton = new javax.swing.JButton();
        roomNoLabel1 = new javax.swing.JLabel();
        roomResultLabel = new javax.swing.JLabel();
        roomNoLabel3 = new javax.swing.JLabel();
        roomNoLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        miniLogo = new javax.swing.JLabel();
        progressLabel = new javax.swing.JLabel();
        exitButton = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(200, 100));
        setUndecorated(true);
        setOpacity(0.0F);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(65, 64, 75));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        roomNoLabel.setFont(new java.awt.Font("Swis721 LtEx BT", 0, 18)); // NOI18N
        roomNoLabel.setForeground(new java.awt.Color(102, 102, 102));
        roomNoLabel.setText("Rooms Available:");

        paymentButton.setBackground(new java.awt.Color(0, 102, 102));
        paymentButton.setFont(new java.awt.Font("Swis721 LtEx BT", 0, 14)); // NOI18N
        paymentButton.setForeground(new java.awt.Color(255, 255, 255));
        paymentButton.setText("Payment");
        paymentButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        paymentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentButtonActionPerformed(evt);
            }
        });

        cancelButton.setBackground(new java.awt.Color(204, 51, 0));
        cancelButton.setFont(new java.awt.Font("Swis721 LtEx BT", 0, 14)); // NOI18N
        cancelButton.setForeground(new java.awt.Color(255, 255, 255));
        cancelButton.setText("Cancel");
        cancelButton.setAlignmentY(0.0F);
        cancelButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        roomPictureLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/SINGLE_RESULT.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(roomPictureLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(roomPictureLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Trajan Pro", 0, 8)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText(".");

        searchResultTable.setFont(new java.awt.Font("Swis721 LtEx BT", 0, 17)); // NOI18N
        searchResultTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Room No.", "Room Type", "No. of Beds", "Price per Day"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        searchResultTable.setRowHeight(25);
        jScrollPane1.setViewportView(searchResultTable);

        reserveButton.setBackground(new java.awt.Color(0, 102, 102));
        reserveButton.setFont(new java.awt.Font("Swis721 LtEx BT", 0, 14)); // NOI18N
        reserveButton.setForeground(new java.awt.Color(255, 255, 255));
        reserveButton.setText("Reserve");
        reserveButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reserveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reserveButtonActionPerformed(evt);
            }
        });

        undoButton.setBackground(new java.awt.Color(204, 51, 0));
        undoButton.setFont(new java.awt.Font("Swis721 LtEx BT", 0, 14)); // NOI18N
        undoButton.setForeground(new java.awt.Color(255, 255, 255));
        undoButton.setText("Undo");
        undoButton.setAlignmentY(0.0F);
        undoButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        undoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                undoButtonActionPerformed(evt);
            }
        });

        roomNoLabel1.setFont(new java.awt.Font("Swis721 LtEx BT", 0, 18)); // NOI18N
        roomNoLabel1.setForeground(new java.awt.Color(102, 102, 102));
        roomNoLabel1.setText("Rooms Reserved:");

        roomResultLabel.setFont(new java.awt.Font("Swis721 LtEx BT", 0, 15)); // NOI18N
        roomResultLabel.setForeground(new java.awt.Color(51, 51, 51));
        roomResultLabel.setText("none");

        roomNoLabel3.setFont(new java.awt.Font("Swis721 LtEx BT", 0, 10)); // NOI18N
        roomNoLabel3.setForeground(new java.awt.Color(102, 102, 102));
        roomNoLabel3.setText("Instruction: To reserve rooms, select a room from the table and click Reserve Button, to cancel previously selected");

        roomNoLabel4.setFont(new java.awt.Font("Swis721 LtEx BT", 0, 10)); // NOI18N
        roomNoLabel4.setForeground(new java.awt.Color(102, 102, 102));
        roomNoLabel4.setText("click the Undo button. Click the payment button to proceed for the payment of the rooms selected.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(roomNoLabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(roomNoLabel4)
                                            .addComponent(roomNoLabel3))
                                        .addGap(62, 62, 62)
                                        .addComponent(jLabel1))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(roomNoLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(roomResultLabel))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(reserveButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(undoButton)
                                .addGap(246, 246, 246)
                                .addComponent(paymentButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cancelButton)))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(roomNoLabel)
                .addGap(8, 8, 8)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 7, Short.MAX_VALUE)
                        .addComponent(roomNoLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(roomNoLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(roomNoLabel1)
                            .addComponent(roomResultLabel))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(paymentButton)
                            .addComponent(reserveButton)
                            .addComponent(undoButton)
                            .addComponent(cancelButton))
                        .addGap(24, 24, 24))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jPanel4.setBackground(new java.awt.Color(65, 64, 75));
        jPanel4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel4MouseDragged(evt);
            }
        });
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel4MousePressed(evt);
            }
        });

        miniLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/midtown2mini.png"))); // NOI18N
        miniLogo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        miniLogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                miniLogoMouseClicked(evt);
            }
        });

        progressLabel.setBackground(new java.awt.Color(65, 64, 75));
        progressLabel.setFont(new java.awt.Font("Trajan Pro", 0, 16)); // NOI18N
        progressLabel.setForeground(new java.awt.Color(255, 255, 255));
        progressLabel.setText("LOGIN > PREFERENCE > RESULT");

        exitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/x_default.png"))); // NOI18N
        exitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitButtonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                exitButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                exitButtonMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(miniLogo)
                .addGap(18, 18, 18)
                .addComponent(progressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exitButton))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(exitButton)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(miniLogo)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(progressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("MIDTOWN HOTEL ONLINE RESERVATION SYSTEM © 2015 ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 684, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(231, 231, 231)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void paymentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentButtonActionPerformed
        
        //checks if the guest have reserved any of the rooms,
        //if yes, proceed to payment transactions
        if(database.getSelectedRoomsCounter() > 0){
            PaymentFrame payment = new PaymentFrame();
            payment.displayFrame();
            this.setVisible(false);
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(jPanel1, "Please select a room "
                    + "from the list to be reserved.");
        }   
        database.getGuestInfo();    // display guest information result on console
    }//GEN-LAST:event_paymentButtonActionPerformed
    
    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
       preferenceFrame prefer = new preferenceFrame();
       prefer.displayFrame();
       this.setVisible(false);
       this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
         //fading in effect
         for(double i=0.0;i<1.0;i=i+0.1){
            String val = i+"F";
            float f = Float.valueOf(val);
            this.setOpacity(f);
            try{
                Thread.sleep(20);
            }catch(Exception e){
            
            }
        }
         
         //Reset room count upon returning to prev window
         database.setRoomCounter(0);
        
         //get the room information from the guest's preference
         database.getRoomNumberbyPref();
         
         //display the Room Numbers of the result on  console
         database.dispRoomNum();
         
         // displays the search result in the panel
         displaySearchResult(); 
         
         //change picture result
         changePicture();
    }//GEN-LAST:event_formWindowOpened
    
    private void jPanel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MousePressed
        //get the X and Y coordinates of the mouse in the Window
        xMouse = evt.getX();
        yMouse = evt.getY();
        
    }//GEN-LAST:event_jPanel4MousePressed

    private void jPanel4MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseDragged
        //get the X and Y coordinates of the mouse in the Screen
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        this.setLocation(x-xMouse,y-yMouse);
    }//GEN-LAST:event_jPanel4MouseDragged

    private void reserveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reserveButtonActionPerformed
        int selectedRow = searchResultTable.getSelectedRow();   //get the seleced row in the table
        selectedRoomNum = (int) searchResultTable.getValueAt(selectedRow,0);    //get the value of the selected row
        String result = " ";
        int temp;
        boolean isAlreadySelected = false;
        
        //Check for duplicate, if true, do not add in the canceled rooms
        temp = (int) searchResultTable.getValueAt(selectedRow,0);
        
        for(int i=0;i<selectedRoomCount;i++){
            if(temp == guestSelectedRooms[i]){
                isAlreadySelected = true;
            }
        }
        
        //if the selected room is not selected by the guest
        if(!isAlreadySelected){
            //add the selected room in the array of selectedRoomNum 
            database.setSelectedRoomOnGuest(selectedRoomNum, true);
            System.out.println("Room " +selectedRoomNum + " is reserved by guest" );
            
            selectedRoomCount++;

            for(int i=0;i<selectedRoomCount;i++){
                result += guestSelectedRooms[i]+",";
            }

            roomResultLabel.setText(result);
            System.out.println(result);
        }else{
            System.out.println(temp + " is already selected. ");
            JOptionPane.showMessageDialog(jPanel1, "Room "+temp + " is already selected. ");
        }
        
    }//GEN-LAST:event_reserveButtonActionPerformed

    private void undoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_undoButtonActionPerformed
        String result = " ";
        if(selectedRoomCount > 0){
            //deselects the previously selected room
            database.setSelectedRoomOnGuest(selectedRoomNum, false);
            System.out.println("Room " +selectedRoomNum + " is reserved by guest" );
            
            selectedRoomCount--;
            guestSelectedRooms[selectedRoomCount] = 0;
            
            for(int i=0;i<selectedRoomCount;i++){
                result += guestSelectedRooms[i]+",";
            }
            roomResultLabel.setText(result);
            System.out.println(result);
        }
    }//GEN-LAST:event_undoButtonActionPerformed

    private void miniLogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miniLogoMouseClicked
       
        
        int status=0; //holds the result status of the confirmation 
        
        //show dialog box for confirmation (status = 0 - yes, 1 - no)
        status = JOptionPane.showConfirmDialog(jPanel2, "Reservation process will be canceled. Do you wish to continue?", 
                "Warning", JOptionPane.YES_NO_OPTION);
        
        if(status == 0){    //if status is yes
            GuestOptionFrame option = new GuestOptionFrame();
            option.dispFrame();
            this.setVisible(false);
            this.dispose();
        }else{
            //do nothing
        }
       
    }//GEN-LAST:event_miniLogoMouseClicked
  
    private void exitButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonMouseEntered
        ImageIcon extbot = new ImageIcon(getClass().getResource("/img/x_focus.png"));
        exitButton.setIcon(extbot);                                   
    }//GEN-LAST:event_exitButtonMouseEntered

    private void exitButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonMouseExited
        ImageIcon extbot = new ImageIcon(getClass().getResource("/img/x_default.png"));
        exitButton.setIcon(extbot);
    }//GEN-LAST:event_exitButtonMouseExited

    private void exitButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonMousePressed
         ImageIcon extbot = new ImageIcon(getClass().getResource("/img/x_clicked.png"));
        exitButton.setIcon(extbot);
    }//GEN-LAST:event_exitButtonMousePressed

    private void exitButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonMouseReleased
         
        int status=0; //holds the result status of the confirmation 
        
        //show dialog box for confirmation (status = 0 - yes, 1 - no)
        status = JOptionPane.showConfirmDialog(jPanel1, "Do you really want to exit?", 
                "Exit", JOptionPane.YES_NO_OPTION);
        
        if(status == 0){    //if status is yes
            System.out.println("status: " + status);
            database.extConnection(); //close database connection
            this.setDefaultCloseOperation(this.EXIT_ON_CLOSE);
            System.exit(0);
        }else{
            //do nothing
        }
    }//GEN-LAST:event_exitButtonMouseReleased

     public void displayFrame() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchResultFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchResultFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchResultFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchResultFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        System.out.println("Search Results:");
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchResultFrame().setVisible(true);
            }
        });
    }
     
    /*
      This will display the search result in the table
      from the result array.
    */
    public void displaySearchResult(){
        int[] results = new int[resultSize];
        results = database.getRoomsNumResult();
        int resultCount = database.getResultCount();
        
        int     data1 = 0;
        String  data2 = "none";
        int     data3 = 0;
        float   data4 = 0;
        
        //create a table model
        DefaultTableModel model = (DefaultTableModel) searchResultTable.getModel();

        for(int i=0;i<resultCount;i++){
            data1 = results[i];
            data2 = database.getSelectedRoomType();
            data3 = database.getSelectedRoomBed();
            data4 = database.getSelectedRoomPrice();
            Object[] rows = { data1, data2, data3, data4 };
            model.addRow(rows);
        }
    }
    
    /**
     * changes picture based on selection of room type.
     */
public void changePicture(){
    
    String roomtype = database.getSelectedRoomType();
    
    switch(roomtype){
        case "Single":
            roomPictureLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/SINGLE_RESULT.png")));
            break;
        case "Twin":
            roomPictureLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/TWIN_RESULT.png")));
            break;
        case "Triple":
            roomPictureLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/TRIPLE_RESULT.png")));
            break;
        case "King":
            roomPictureLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/KING_RESULT.png")));
            break;
        case "Suite":
            roomPictureLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/SUITE_RESULT.png")));
            break;    
        default:
            break;
    }
    

}
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel exitButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel miniLogo;
    private javax.swing.JButton paymentButton;
    private javax.swing.JLabel progressLabel;
    private javax.swing.JButton reserveButton;
    private javax.swing.JLabel roomNoLabel;
    private javax.swing.JLabel roomNoLabel1;
    private javax.swing.JLabel roomNoLabel3;
    private javax.swing.JLabel roomNoLabel4;
    private javax.swing.JLabel roomPictureLabel;
    private javax.swing.JLabel roomResultLabel;
    private javax.swing.JTable searchResultTable;
    private javax.swing.JButton undoButton;
    // End of variables declaration//GEN-END:variables
}
